generar_sugerencias:
  name: Generar Sugerencias de IA
  description: "Envía los patrones detectados a un modelo de IA para generar ideas de automatización."
  fields:
    proveedor:
      name: Proveedor de IA
      description: "Selecciona el proveedor de IA para generar las sugerencias."
      required: false
      selector:
        select:
          options:
            - OpenAI
            - Anthropic
            - Google
            - Groq
            - LocalAI
            - Ollama
